site_name: MFEM
docs_dir: 'src'

markdown_extensions:
- extra  # allow markdown in <div markdown="1">
- fenced_code  # GitHub style code blocks, e.g. ```python, see http://highlightjs.readthedocs.org/en/latest/css-classes-reference.html for a list of languages

repo_url: https://github.com/mfem/mfem
remote_name: github

pages:
- Home: index.md
- Features: features.md
- Examples: examples.md
- Documentation:
  - 'Building MFEM': building.md
  - 'Serial Tutorial': serial-tutorial.md
  - 'Parallel Tutorial': parallel-tutorial.md
  - 'Electromagnetics': electromagnetics.md
  - 'Meshing': meshing.md
  - '_Mesh Formats': mesh-formats.md   # pages starting with '_' are hidden from the menu
  - 'Performance': performance.md
  - 'Publications': publications.md
  - 'About': about.md
- Gallery: gallery.md
- Download: download.md

theme_dir: template

include_next_prev: false  # turn off next/previous buttons

google_analytics: ['UA-101697-3', 'mfem.org']
