site_name: MFEM
docs_dir: 'src'

markdown_extensions:
- extra  # allow markdown in <div markdown="1">
- fenced_code  # GitHub style code blocks, e.g. ```python, see http://highlightjs.readthedocs.org/en/latest/css-classes-reference.html for a list of languages

homepage_url: http://mfem.org
repo_url: https://github.com/mfem/mfem
remote_name: github

pages:
- Home: index.md
- Features: features.md
- Examples: examples.md
- Documentation:
  - '_News': news.md   # pages starting with '_' are hidden from the menu
  - 'Building MFEM': building.md
  - 'Serial Tutorial': serial-tutorial.md
  - 'Parallel Tutorial': parallel-tutorial.md
  - 'Finite Elements': fem.md
  - '_Bilinear Form Integrators': bilininteg.md
  - '_Linear Form Integrators': lininteg.md
  - '_Linear Interpolators': lininterp.md
  - 'Electromagnetics': electromagnetics.md
  - 'Meshing': meshing.md
  - '_Mesh Formats': mesh-formats.md
  - '_Mesh Format v1.x': mesh-format-v1.x.md
  - 'Performance': performance.md
  - 'Code Overview': code-overview.md
  - 'Publications': publications.md
  - 'About': about.md
- Gallery: gallery.md
- Download: download.md

theme:
  name: mkdocs
  custom_dir: template

google_analytics: ['UA-101697-3', 'mfem.org']
